wait_location:
  pos: [-3.275, -4.703, 0.000]
  ori: [0.000, 0.000, -0.650, 0.760]
  ang: 0.0
post_location:
  pos: [-2.512, -4.354, 0.000]
  ori: [0.000, 0.000, -0.049, 0.999]
  ang: 1.145
observe_location:
  pos: [-1.158, -7.241, 0.000]
  ori: [0.000, 0.000, 0.313, 0.950]
  ang: 0.240
build_location:
  pos: [0.837, -5.948, 0.000]
  ori: [0.000, 0.000, -0.012, 1.000]
  ang: 0.350
  wait: 0.805
  check: [1.537, -5.948, 0.0]
couch_location:
  pos: [0.291, -5.886, 0.000]
  ori: [0.000, 0.000, 0.666, 0.746]
  ang: 0.805
  wait: 0.805
  check: [0.363, -5.205, 0.000]

urls:
  advance: /_/I/advance
  observe_start: /_/I/observe_start
  observe_end: /_/I/observe_end
  start: /_/I/start
  check_grab: /_/I/check_grab
  ignored: /_/I/ignored
  check_end: /_/I/check_end

log_topics:
  start: /datalogger/start
  stop: /datalogger/stop

sound_names:
  acknowledge: alright.wav
  interrupt: interrupt.wav
  build_complete: thanks.wav
  verify: verify.wav
  searching: looking.wav
  not_found: not_found.wav
