string next_state # The next state that we need to transition to

# Constants for the possible values of next_state
string WAIT=wait
string OBSERVE=observe
string INTERRUPT=interrupt
string ROAM1=roam1
string ROAM2=roam2
---
bool success
string message
