#!/usr/bin/env python
# Starts up and runs the state machine

from christmas_state_machine.state_machines import ChristmasStateMachine
import rospy

log_lvls = {
   'DEBUG': rospy.DEBUG,
   'INFO': rospy.INFO,
   'WARN': rospy.WARN,
   'ERROR': rospy.ERROR,
   'FATAL': rospy.FATAL,
   'debug': rospy.DEBUG,
   'info': rospy.INFO,
   'warn': rospy.WARN,
   'error': rospy.ERROR,
   'fatal': rospy.FATAL,
}

if __name__ == "__main__":
    """
    Initialize the node
    """
    log_lvl = rospy.get_param("/logger_lvl", 'INFO')
    rospy.init_node('christmas_state_machine', log_level=log_lvls[log_lvl])
    sm = ChristmasStateMachine()
    sm.execute()
    rospy.spin()
